name: Check Permit Availability

on:
  workflow_dispatch:        # Manual trigger for GitHub UI and POST requests
    inputs:
      trigger:
        description: 'Enhances UI display with where job triggered from'
        type: string
        default: 'UI'

run-name: ${{ format('Check Permit Availability - {0}', github.event.inputs.trigger) }}

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Download state artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: state-artifact
      #     path: .
      #     fail-on-unmatched-artifact: false

      - name: Run the script
        run: python script.py

      - name: Upload state artifact
        uses: actions/upload-artifact@v4
        with:
          name: state-artifact
          path: state.json
          overwrite: true