name: Check Permit Availability

on:
  workflow_dispatch:        # Manual trigger for GitHub UI and POST requests

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the script
        run: python script.py

      - name: Dump GitHub event context
        env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: echo "$EVENT_CONTEXT"
