name: Check Permit Availability

on:
  workflow_dispatch:        # Manual trigger for GitHub UI and POST requests
    inputs:
      trigger:
        description: 'Enhances UI display with where job triggered from'
        type: string
        default: 'UI'

run-name: ${{ format('Check Permit Availability - triggered by {0}', github.event.client_payload && 'Cron Job' || 'UI') }}

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the script
        run: python script.py

      - name: Print inputs context
        env:
          INPUTS_CONTEXT: ${{ toJSON(inputs) }}
        run: echo "$INPUTS_CONTEXT"
